/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShellPageRouteImport } from './routes/_shell/$page'
import { Route as ShellPrivacyRouteImport } from './routes/_shell/privacy'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ShellDocsInstallationRouteImport } from './routes/_shell/docs/installation'
import { Route as DocsComponentIndexRouteImport } from './routes/docs/component/index'
import { Route as ShellDocsComponentSlugRouteImport } from './routes/_shell/docs/component/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPageRoute = ShellPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPrivacyRoute = ShellPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShellRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDocsInstallationRoute = ShellDocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => ShellRoute,
} as any)
const DocsComponentIndexRoute = DocsComponentIndexRouteImport.update({
  id: '/docs/component/',
  path: '/docs/component/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDocsComponentSlugRoute = ShellDocsComponentSlugRouteImport.update({
  id: '/docs/component/$slug',
  path: '/docs/component/$slug',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$page': typeof ShellPageRoute
  '/privacy': typeof ShellPrivacyRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/installation': typeof ShellDocsInstallationRoute
  '/docs/component/': typeof DocsComponentIndexRoute
  '/docs/component/$slug': typeof ShellDocsComponentSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$page': typeof ShellPageRoute
  '/privacy': typeof ShellPrivacyRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/installation': typeof ShellDocsInstallationRoute
  '/docs/component': typeof DocsComponentIndexRoute
  '/docs/component/$slug': typeof ShellDocsComponentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_shell/$page': typeof ShellPageRoute
  '/_shell/privacy': typeof ShellPrivacyRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_shell/docs/installation': typeof ShellDocsInstallationRoute
  '/docs/component/': typeof DocsComponentIndexRoute
  '/_shell/docs/component/$slug': typeof ShellDocsComponentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$page'
    | '/privacy'
    | '/components/$slug'
    | '/components/'
    | '/docs/'
    | '/docs/installation'
    | '/docs/component/'
    | '/docs/component/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$page'
    | '/privacy'
    | '/components/$slug'
    | '/components'
    | '/docs'
    | '/docs/installation'
    | '/docs/component'
    | '/docs/component/$slug'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_shell/$page'
    | '/_shell/privacy'
    | '/components/$slug'
    | '/components/'
    | '/docs/'
    | '/_shell/docs/installation'
    | '/docs/component/'
    | '/_shell/docs/component/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentIndexRoute: typeof DocsComponentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/$page': {
      id: '/_shell/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof ShellPageRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/privacy': {
      id: '/_shell/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ShellPrivacyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/docs/installation': {
      id: '/_shell/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof ShellDocsInstallationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/docs/component/': {
      id: '/docs/component/'
      path: '/docs/component'
      fullPath: '/docs/component/'
      preLoaderRoute: typeof DocsComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/docs/component/$slug': {
      id: '/_shell/docs/component/$slug'
      path: '/docs/component/$slug'
      fullPath: '/docs/component/$slug'
      preLoaderRoute: typeof ShellDocsComponentSlugRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellPageRoute: typeof ShellPageRoute
  ShellPrivacyRoute: typeof ShellPrivacyRoute
  ShellDocsInstallationRoute: typeof ShellDocsInstallationRoute
  ShellDocsComponentSlugRoute: typeof ShellDocsComponentSlugRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellPageRoute: ShellPageRoute,
  ShellPrivacyRoute: ShellPrivacyRoute,
  ShellDocsInstallationRoute: ShellDocsInstallationRoute,
  ShellDocsComponentSlugRoute: ShellDocsComponentSlugRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentIndexRoute: DocsComponentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
