/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageRouteImport } from './routes/$page'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsComponentIndexRouteImport } from './routes/docs/component/index'
import { Route as DocsComponentSlugRouteImport } from './routes/docs/component/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentIndexRoute = DocsComponentIndexRouteImport.update({
  id: '/docs/component/',
  path: '/docs/component/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentSlugRoute = DocsComponentSlugRouteImport.update({
  id: '/docs/component/$slug',
  path: '/docs/component/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/component/$slug': typeof DocsComponentSlugRoute
  '/docs/component/': typeof DocsComponentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/component/$slug': typeof DocsComponentSlugRoute
  '/docs/component': typeof DocsComponentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/component/$slug': typeof DocsComponentSlugRoute
  '/docs/component/': typeof DocsComponentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/components/$slug'
    | '/docs/installation'
    | '/components/'
    | '/docs/'
    | '/docs/component/$slug'
    | '/docs/component/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/components/$slug'
    | '/docs/installation'
    | '/components'
    | '/docs'
    | '/docs/component/$slug'
    | '/docs/component'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/components/$slug'
    | '/docs/installation'
    | '/components/'
    | '/docs/'
    | '/docs/component/$slug'
    | '/docs/component/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentSlugRoute: typeof DocsComponentSlugRoute
  DocsComponentIndexRoute: typeof DocsComponentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/component/': {
      id: '/docs/component/'
      path: '/docs/component'
      fullPath: '/docs/component/'
      preLoaderRoute: typeof DocsComponentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/component/$slug': {
      id: '/docs/component/$slug'
      path: '/docs/component/$slug'
      fullPath: '/docs/component/$slug'
      preLoaderRoute: typeof DocsComponentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentSlugRoute: DocsComponentSlugRoute,
  DocsComponentIndexRoute: DocsComponentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
